language: android
jdk: oraclejdk8
sudo: false
addons:
  apt:
    packages:
    - lynx
android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.1
  - android-26
  - android-22
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-22
before_install: chmod +x gradle/buildWithTravis.sh
before_script:
  - android list targets
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean build connectedCheck
after_failure: lynx -dump app/build/outputs/gnag/gnag.html
after_success:
  - ./gradle/buildWithTravis.sh
env:
  global:
  - secure: TZ11ozcJozynKr37pRPY2METtIEsDav//mE7wiCEumM4W59QMMnVqjJGTxBipbAuAX36PnEg0/jZbHfXjVJ4py9tGIDB3nlDULqRN/0Ddko/y4gzPQLVpvD22UU0N6g/r0tTJ4H775nxWF07Jw4nohtit7GVZS9Z/dgYvSFE7r2blnflzBBqqRZ2godE0r+8oZV6bRqpo/XxLEqiaBJS7cNbfZIKb+EnwPPuslA4ZdqPAM6U8rV43rzP4oi0M0Z+33s8D/ppDNhU6fPtt8cLIpJaMR5hLowg/U1y919Gp6wpA75Ttx9wZuxBFeAyJxKhJ0O5Myt21Soyw4blayUqqba3i/Nh+voNogwa9JUWzG/AOPDRQqCqKG0yswoRiKfTprSS6w487E1mHpLygftkaTAYKU3HYE/MZl8VYw6FUBC3QSNL5IJ/K8+k5K+Q9xwRBh9W57sclDcAq4fchrH4SKnYQ4GwFpLzyZBblL02ya+wi1kFxLlyHHPZNV/ZLAFG5uc/q1xfs3G6IPcjaRDWk2Ole0vTfqoCV1BVGKJ4+/M4XC+A6ML09CyOYzyu0mZFqWBzyCN3k3Up9sP+ysA9Et28ZO2JbCass3EV8hn1kF4eGwLgOtRpklZCttwLYPqmMjZQeFevF5+QRSZC80eHjf7kxQDwdBMja+dQS3xrIyE=
  - secure: LPWlPox2p8IiKQ8McuuK9e5jkuizp5A2m1nRjyGaq0FYyZD0rQ/AipiE6J25uyemxw11ZyJwno5pdrqytTQxDP2M4hVxMKU5vqvjVrVPDkSfTc0/xjW6efA+F2TBMzQavwANgS4y0OkKe18yZMPva/5sW9JbAuhbVDZn+rjRgoc7BSjX/xqw1QFmAmQXAfNxaUxpBmXSQbiZX67bFem9C77Ymhcd4bwvVu67ukVEQ+BhJw94y95j7enUBA9ioMQN8LIMH+/2U+YwHgQKaBYDQ1Y4PTxfOD8lis7z9m5ODXjCIEINJ2DXv4LM91oGtffQDftX+7P8J8oOF+p5AQWH85xgQh4bsuvRDJo0KXrUkTZ5knx76t+po9pxuLes3Mt0ykqAs5orpMBFPB6xYM7GWmzrGdIIHa4QdwmQyu8DyLCbRn3uCaIsEmxu6t+QOlEG9fEqog+TrRoPoM9ExzXQ9hyDAAqjhEVemhaqv5u8jjNtsV6s2MZyBEdH/BMbKEx9eBCsGCi5k++FPnIWB8ekUSsN8NUZvUXLZ3+7nEvLHjRBBonlJGuVuRjYpsOoCcaDvN3BVfDjA7+Ps7Y7Ci8SitzTYC/YLPNBp91oCjX7kDG13nOFgSiWZaUBrdekB5ush4TPxf4UOZuPHjadFin+c03iFn3cWKJo+Fd/66OLPV0=
  - secure: AHJQRYhNggAH/SSrIMjqTLZYyjc5BFQV8utlyF11sDmraWCs5IN0ZXc5CpKFQHwLgJjx5gObuHErXOSHDE5M9g/OM2OO5/hTnOSYC9xxNMmPtHf0J7rUnG/j4tICMWPjBsL/s7mZCxBMJ/AFNW2DGslIQDaSZJFENVvCehWZakDOV9pnZbYia47FJWwdW977OMKd/q3jOOSVMcSo6ZRNfjUyBe8gCW3oTJFh1N1EAhFog6xSnK45DoVW5cU6uWowVVsI39iUalmmUmCLm55w75IqmNTFcm7JHEdU/wbV034qI1GK3Oe6PSUQgC6JVBqw4ssjnp3qhAP6SeDA5UJNBcDplWMcqbIBVxfOp48QqWlgLEGp/uyr6KTYb+ZupKFVAEFXEgOUnNMXfJ51bwDBgFVdcy9n8QyIJn1tX5+Gj36C6kMBHIMgGraUZ+AT7ZMHfTrByD78Qk169/a379VsKPnf/ft6XzARXXbu87qJ0kHWbC7ugDeCfjjCUCLQ6rf3sdLj1TzK/qpvOj185wOyv+s0zUfFFuekXRux9itC0CDOgxw8XE0Li/Sp9SGfoN77m97bSy6+IHuM2RDKCleICC3fedwPPZVA0UdL6uL+bfBuHQK9/H6qV/xlJN+PDf6MbDCnsMsChp6VUBAHt/r1+K/ebB2nXzgdrDN9HCzZzuo=
  - secure: eC9/LKrCGhhP4xlePSHQ1K6XPhO4dNHwFfCDLeML/zzsOfyB9bENRfcoqrZ2GZ3UWigga8X8+lWVK2R+feRjNYrdR7oPXmvHwptSXS5+ECSkvAh5dusLIVKhDnsMsyXzSLV2eP8KMNGt6oBx28v4o9GtXTyLE9zIGQqeMEtwA0BRoqyE5MxEj6KWrwauNuKBfOQ/cdYN71KVwZ7VEA/2QhHvsfbNb9HEgzwy+mtPufOz6nucNfrR3Rwk5x+Kt9etOrdzWiX6rRtML7uN/IHXp2vbxHDgEaxmtrgQduqGRMacarvHiloU3QFIHvqszjGwspySJ/eZLPqELwmBBNGZmwUj6OrcDs9vG8gYHXneTXlNCLHJVLIEHxm+lYGejsPkytSUSNX1LtJnXuAaE9Z2BFudTx0pYKdWdMQZ/Ne2pUKTNZMyrMBfEazia9EeVd9C6DCqebXEjuM4w3y5kkigNhHvNKqH88GztcYXuxQ98saHIg9srHs6bavWp86sX+5FOWltTX3ZaQpMQJpAQoxI8S6gi/O1E17tqYmNWWW4Sh7yqB6IkgC6mciCD2UNCaLFiNeRirsK6M6TIun8oHXOTT1gG9ADPflflIU0xy/alCnC8T9hNiiGtsAmDMFdNQvvRQRwLpBb0MKE0gQASCjQZ0/18RWyZOO9bsUGuIq4IcA=
